language: node_js
node_js:
  - "15"
dist: trusty
sudo: required
branches:
  only:
    - feat/travis-ci
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --base-href https://github.com/UgoPerniceni/code-roulette-front-web/
